name: Deploy Infrastructure


on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Stack Security
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/security.yml \
            --stack-name SecurityGroups-Daniel-Leon \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy Stack EC2
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/ec2.yml \
            --stack-name EC2-Daniel-Leon \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy Stack ALB-ASG
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/alb-asg.yml \
            --stack-name ALB-ASG-Daniel-Leon \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides VpcId=vpc-06060a3f77407e9b2 SubnetIds="subnet-0099321b7f6f65f3d,subnet-0eae0f2aa3fd28989"

      - name: Deploy Stack Automation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/automation.yml \
            --stack-name Automation-Daniel-Leon \
            --capabilities CAPABILITY_NAMED_IAM